### ISSUE TITLE
Add possibility to add percentage fee

### ISSUE THREAD

**Issue by yavuzaydin** [mageprince/magento2-paymentfee#1]
Please add the possibility to add a percentage based fee per payment method.

**Comment by mageprince** [comment]
@yavuzaydin I will add this functionality in the next version of the module.

**Comment by yavuzaydin** [comment]
Any idea when we can expect the next version?

**Comment by mageprince** [comment]
@yavuzaydin Please use the latest version of the module. There four configuration options for the price.
1. Fixed Price
2. Percentage Price
3. Per row
4. Per Item
