### ISSUE TITLE
Manage Payment Fee not showing

### ISSUE THREAD

**Issue by wdhrudra** [mageprince/magento2-paymentfee#10]
As per your demo, under store, "Manage Payment Fee" is not showing. Can you please update the code?

**Comment by mageprince** [comment]
Hi @wdhrudra, Thanks for letting us know your concerns. Unfortunately, we still don't have a demo for the Payment Fee extension. You can add payment fee and change configuration from **Admin->Stores->Configurations->MagePrince->Payment Fee**
