### ISSUE TITLE
How about including it in packagist?

### ISSUE THREAD

**Issue by ioweb-gr** [mageprince/magento2-paymentfee#11]
Hi, do you think you could add the repo to packagist for easier deployment? It would help a lot

**Comment by mageprince** [comment]
Hi @ioweb-gr Thank you for your suggestion.
We have added the "Payment Fee" module to packagist.
You can now install this module by `composer require mageprince/magento2-paymentfee`

**Comment by ioweb-gr** [comment]
Thank you, much appreciated
