### ISSUE TITLE
Install php error CalculatorInterface not found

### ISSUE THREAD

**Issue by kennedyabitbol** [mageprince/magento2-paymentfee#12]
Hi,

When trying to install (2.1.0 or 2.1.1) with magento 2.3.4, i got this error:

```
Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec 98.5 MiBPHP Fatal error:  Interface 'Mageprince\Paymentfee\Model\Calculation\Calculator\CalculatorInterface' 
```

Edited: Solvem path corrected, thanks for your reply.

**Comment by mageprince** [comment]
Hi @kennedyabitbol, thank you for your report.
We are unable to reproduce this issue on Magento 2.3.x or Magento 2.4.x. Please make sure you follow the correct module path `app/code/Mageprince/Paymentfee`

For more information, you can check the same issue thread in our other module here: https://github.com/mageprince/magento2-productAttachment/issues/68
