### ISSUE TITLE
Multicurrency issue & tax amount at invoicing

### ISSUE THREAD

**Issue by peter-k77** [mageprince/magento2-paymentfee#13]
Hi,
Thank you for all improvements made in the latest versions.
Unfortunately I still do have 2 issues:

**1.** in multi-currency store, there is **no amount in base currency** if the order is placed in other than base currency - see screenshot:
![Order](https://user-images.githubusercontent.com/48489426/102701655-8ec91f00-4259-11eb-95fe-b597dec71054.png)
Payment fee should be 3€ and 81 Kč (base currency, fx rate = 27 Kč/€)

**2.** when an order is **invoiced**, tax is handled incorrectly (regardless of currency) - see screenshot:
![Order-invoiced](https://user-images.githubusercontent.com/48489426/102701667-a3a5b280-4259-11eb-97c2-f64e82cde04c.png)
See only calculation in €:
Total paid = 97.98€ = 92.0 + 3.5 + 3/1.21 [Tax rate is 21%]
So obviously the **invoiced amount does not include VAT on the payment fee.**

_My store set up:_
Currency: 1€ = 27Kč
Base currency = Kč
Tax rate = 21%
Payment fee = 66.94 Kč [2.48 €]  => incl. tax = 81 Kč [3.00 €]
Calculate Tax = Yes
Display Payment Fee = Including Tax
I am using the latest version of the extension

**Comment by mageprince** [comment]
Hi @peter-k77 This is fixed with the latest version(2.1.2) of the module.
Related commit: https://github.com/mageprince/magento2-paymentfee/commit/29c070dc1b21f5aa6cb30407eca88f3591da6fea
