### ISSUE TITLE
[Question] What are the minimum requirements 

### ISSUE THREAD

**Issue by Coosos** [mageprince/magento2-paymentfee#16]
Hi Mageprince,

I would like to know the versions of PHP and magento that we must respect at least for the contribution :smile:
(_I should push an MR to use web apis instead of a controller_)

It would also be interesting if it was specified in the composer.json :+1: 

Thank you, Good day

**Comment by mageprince** [comment]
Hi @Coosos 
The Php version should be 7.4 with the latest version of Magento 2.4.x. We recently release this module compatible with the Magento 2.4.x community and Enterprise edition. We will update the composer.json soon.

Thanks again for your recent contribution. We released a new version with your fixes on Magento Marketplace, GitHub, and Packagist.
https://github.com/mageprince/magento2-paymentfee/releases/tag/2.1.3
https://packagist.org/packages/mageprince/magento2-paymentfee

**Comment by Coosos** [comment]
Hi @mageprince 

After verification, magento still indicates support for 2.3 and php for 7.3.

At least its versions must be taken into account :smile:

**Comment by mageprince** [comment]
Hi @Coosos 

Magento marketplace supports Magento 2.4 for both community and enterprise editions.
https://marketplace.magento.com/prince-magento2-paymentfee.html

![image](https://user-images.githubusercontent.com/24751863/108949483-80004d80-768a-11eb-95c7-87fb2b58a48b.png)
![image](https://user-images.githubusercontent.com/24751863/108949587-af16bf00-768a-11eb-9cfc-3829d6318e2b.png)

**Comment by Coosos** [comment]
Hi @mageprince 

_My previous message may not have been well worded_

Yes, it supports 2.4 and 2.3, so we must be compatible with both versions :+1:

Magento 2 life cycle : https://devdocs.magento.com/release/lifecycle-policy.html

Cordially ;
