### ISSUE TITLE
Issue: Payment fee is not added if VAT field is filled out

### ISSUE THREAD

**Issue by thomas-mohanty** [mageprince/magento2-paymentfee#19]
If a customer adds his VAT information in the checkout, the payment fee does not get added.

Tested with Magento Version 2.3.2 and 2.3.6
Tested with both default and custom payment methods
Changing the tax settings in backend does not seem to change this result

**Comment by mageprince** [comment]
Hi @thomas-mohanty We are unable to find any issue with Tax configuration. It would be good if you provide a video of the issue.
