### ISSUE TITLE
Tax not applied when editing order from admin

### ISSUE THREAD

**Issue by andy1786** [mageprince/magento2-paymentfee#22]
Hello,

Payment fee is not working when I try to edit an order in admin. It is working very good when adding an order to frontend, but in admin is not working when editing an order to adding a new order via admin panel. I've tried with guest and customer.

**Comment by mageprince** [comment]
Dear @andy1786, thank you for your report.
We have fixed this issue with commit:  https://github.com/mageprince/magento2-paymentfee/commit/42ef1550144fa2b366441a81319ddd178c730198

This fix will be available with the new version (2.1.6) to the Magento Marketplace.
