### ISSUE TITLE
Compilation Error on Module Enable

### ISSUE THREAD

**Issue by NoSGR** [mageprince/magento2-paymentfee#23]
Hello,

I've just tried to install the module on Magento 2.3 with PHP 7.1 and i'm getting this error when i'm trying to compile:

PHP Parse error:  syntax error, unexpected 'State' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /home/***/www/vendor/prince/magento2-paymentfee/Helper/Data.php on line 59

**Comment by mageprince** [comment]
Hi @NoSGR, thank you for your report.

This is fixed with commit:  9bdb20a4f5f91754fbf450d7ee37bc8008ab86e0
We have added a new version(2.1.7) on Magento Marketplace. You can upgrade it once it is approved by the Magento marketplace. Normally it would take 2-3 hrs.

**Comment by NoSGR** [comment]
Thank you very much! It works now!

**Comment by mageprince** [comment]
Hi @NoSGR Glad to know that your issue has been resolved now.

Can you please write a review on Google: https://g.page/r/CeQIoyaydOkKEB0/review

It would help us a lot. Thank you in advance.
