### ISSUE TITLE
where's the source code?

### ISSUE THREAD

**Issue by YiffyToys** [mageprince/magento2-paymentfee#26]
where's the source code?

**Comment by sfritzsche** [comment]
https://github.com/mageprince/magento2-paymentfee/tree/develop-2.1.7

**Comment by YiffyToys** [comment]
Okay. That's a VERY strange branching strategy.

**Comment by mageprince** [comment]
Hi @YiffyToys You can download the latest free version of the payment fee extension from https://marketplace.magento.com/prince-magento2-paymentfee.html
