### ISSUE TITLE
Not working with Amasty Checkout

### ISSUE THREAD

**Issue by Yavonz15** [mageprince/magento2-paymentfee#3]
If I install the module on my project that has Amasty Checkout. The checkout loads to infinity without ever completing itself completely

**Comment by Yavonz15** [comment]
any updates for me?

**Comment by mageprince** [comment]
@Yavonz15 Sorry for the inconvenience. This module is not tested with third-party extensions. However, this module developed with default Magento classes so it should be worked with third-party extensions. Please contact your third-party extension provider.
