### ISSUE TITLE
after integrate the paymentfee is not invisible on Front on checkout payment page

### ISSUE THREAD

**Issue by solanki9** [mageprince/magento2-paymentfee#4]
after integrate the paymentfee is not invisible on Front on checkout payment page

**Comment by mageprince** [comment]
Hi @solanki9 
This module is working fine with Magento 2.2.x and 2.3.x versions of the Magento. Please check the following scenarios to debug the issue.

1. Check ExtraFee configurations store vice from admin
2. Make sure you properly configured module with all the commands
3. Check with default Magento Luma Theme
4. Uninstall all third party modules and check
5. Check with default Magento Setup
