### ISSUE TITLE
Paypal I can't put extra charge

### ISSUE THREAD

**Issue by victorsanva** [mageprince/magento2-paymentfee#6]
Hello,

Plugin is working fine to me, but paypal option is not showing me,

Magneto Version 2.3.4, paypal configuration is with the version incluided in magento, anything strange.

thank you
![90309686-e4c43980-deea-11ea-9c38-5a09c9c1831d](https://user-images.githubusercontent.com/60794660/93663525-f1e3c380-fa68-11ea-9489-41467d475099.png)

**Comment by mageprince** [comment]
Hi @victorsanva Thanks for your report.

**Please make sure you enabled the PayPal payment method from the configuration. Sales->Payment Methods->PayPal**

![paypal](https://user-images.githubusercontent.com/24751863/93670398-b83aa900-fab8-11ea-848a-960941ca027a.jpeg)


We are unable to reproduce the issue. We can see PayPal payment method in payment fee dropdown.

![mageprince_paymentfee](https://user-images.githubusercontent.com/24751863/93670412-d7d1d180-fab8-11ea-9e92-2eab5a032709.jpeg)

**Comment by mageprince** [comment]
Hi @victorsanva We have changed the logic to show payment method from enabled only to show all in the configuration. You can try the latest version of the module. You can download the latest version of the module from Magento Marketplace or download the latest code here from GitHub.
