### ISSUE TITLE
Payment Fee is added on each partial invoice.

### ISSUE THREAD

**Issue by victortodoran** [mageprince/magento2-paymentfee#7]
Steps to reproduce:
1. Place order with at least two products.
2. Create to separate invoices

Expected result:
Payment fee is taken into account once.

Actual result:
Payment fee is applied to each invoice causing a mismatch in totals.
![image](https://user-images.githubusercontent.com/25669334/97305167-6d554380-1865-11eb-92f4-607e8d61ae38.png)

**Comment by mageprince** [comment]
Hi @victortodoran, Thanks for your patience. This issue is fixed now in the latest version of the module.
Related commit: https://github.com/mageprince/magento2-paymentfee/commit/595f6f9b205bbf2f719385fc1982dabf07b46c68
